#ifndef __G3507_HW_CONFIG_H
#define __G3507_HW_CONFIG_H

#include "ti/driverlib/dl_gpio.h" /* GPIO_Pin_x + GPIOA/B 原语，其余枚举值在 Enroll.c 展开时由 Enroll_Internal.h 提供 */

/*
 * G3507_hw_config.h 板级硬件映射宏
 * 只维护实际用到的端口/引脚/IOMUX，注册和查找都在这里完成。
 */

/* LED 板级映射 */
#define HW_LED_MAP(X) \
    X(LED1, GPIOB, DL_GPIO_PIN_14)\
    X(LED2, GPIOA, DL_GPIO_PIN_29)\
    X(LED3, GPIOA, DL_GPIO_PIN_28)\
    X(Buzzer1, GPIOA, DL_GPIO_PIN_14)

/* KEY 板级映射 */
#define HW_KEY_MAP(X) \
    X(KEY1, GPIOB, DL_GPIO_PIN_21)\
    X(KEY2, GPIOA, DL_GPIO_PIN_27)\
    X(KEY3, GPIOA, DL_GPIO_PIN_26)\
    X(KEY4, GPIOB, DL_GPIO_PIN_23)

/* USART0 板级映射 */
#define HW_USART0_TX_PORT GPIOA
#define HW_USART0_TX_PIN  DL_GPIO_PIN_10
#define HW_USART0_RX_PORT GPIOA
#define HW_USART0_RX_PIN  DL_GPIO_PIN_11

#define G3507_USART0_TX_IOMUX IOMUX_PINCM21
#define G3507_USART0_TX_FUNC  IOMUX_PINCM21_PF_UART0_TX
#define G3507_USART0_RX_IOMUX IOMUX_PINCM22
#define G3507_USART0_RX_FUNC  IOMUX_PINCM22_PF_UART0_RX

/* USART1 板级映射 */
#define HW_USART1_TX_PORT GPIOA
#define HW_USART1_TX_PIN  DL_GPIO_PIN_8
#define HW_USART1_RX_PORT GPIOA
#define HW_USART1_RX_PIN  DL_GPIO_PIN_9

#define G3507_USART1_TX_IOMUX IOMUX_PINCM19
#define G3507_USART1_TX_FUNC  IOMUX_PINCM19_PF_UART1_TX
#define G3507_USART1_RX_IOMUX IOMUX_PINCM20
#define G3507_USART1_RX_FUNC  IOMUX_PINCM20_PF_UART1_RX

/* USART2 板级映射 */
#define HW_USART2_TX_PORT GPIOB
#define HW_USART2_TX_PIN  DL_GPIO_PIN_15
#define HW_USART2_RX_PORT GPIOB
#define HW_USART2_RX_PIN  DL_GPIO_PIN_16

#define G3507_USART2_TX_IOMUX IOMUX_PINCM32
#define G3507_USART2_TX_FUNC  IOMUX_PINCM32_PF_UART2_TX
#define G3507_USART2_RX_IOMUX IOMUX_PINCM33
#define G3507_USART2_RX_FUNC  IOMUX_PINCM33_PF_UART2_RX

#define HW_USART_MAP(X) \
    X(API_USART1, API_USART_CORE_UART0, HW_USART0_TX_PORT, HW_USART0_TX_PIN, HW_USART0_RX_PORT, HW_USART0_RX_PIN)\
    X(API_USART2, API_USART_CORE_UART1, HW_USART1_TX_PORT, HW_USART1_TX_PIN, HW_USART1_RX_PORT, HW_USART1_RX_PIN)\
    X(API_USART3, API_USART_CORE_UART2, HW_USART2_TX_PORT, HW_USART2_TX_PIN, HW_USART2_RX_PORT, HW_USART2_RX_PIN)

/* TIM 板级映射：
 * - API_TIM1 → TIMG0: PID 控制节拍 (1ms)
 * - API_TIM2 → TIMG6: 编码器读取节拍 (1ms, 每 20ms 快照)
 * - API_TIM3 → TIMG7: 杂务节拍 (1ms, 按键/printf/时间戳)
 */
#define HW_TIM_MAP(X) \
    X(API_TIM1, API_TIM_CORE_TIMG0) \
    X(API_TIM2, API_TIM_CORE_TIMG6) \
    X(API_TIM3, API_TIM_CORE_TIMG7)

/* PWM 板级映射：PA16 -> TIMA1 CCP1，PA17 -> TIMA1 CCP0。 */
#define G3507_PWM_TIMA1_CH1_PORT  GPIOA
#define G3507_PWM_TIMA1_CH1_PIN   DL_GPIO_PIN_16
#define G3507_PWM_TIMA1_CH1_IOMUX IOMUX_PINCM38
#define G3507_PWM_TIMA1_CH1_FUNC  IOMUX_PINCM38_PF_TIMA1_CCP1

#define G3507_PWM_TIMA1_CH0_PORT  GPIOA
#define G3507_PWM_TIMA1_CH0_PIN   DL_GPIO_PIN_17
#define G3507_PWM_TIMA1_CH0_IOMUX IOMUX_PINCM39
#define G3507_PWM_TIMA1_CH0_FUNC  IOMUX_PINCM39_PF_TIMA1_CCP0

#define HW_PWM_MAP(X) \
    X(API_PWM_TIM1, API_PWM_CH1, API_PWM_CORE_TIMA1, API_PWM_CORE_CCP0, G3507_PWM_TIMA1_CH0_PORT, G3507_PWM_TIMA1_CH0_PIN) \
    X(API_PWM_TIM1, API_PWM_CH2, API_PWM_CORE_TIMA1, API_PWM_CORE_CCP1, G3507_PWM_TIMA1_CH1_PORT, G3507_PWM_TIMA1_CH1_PIN)

/* ADC 板级映射*/
#define G3507_ADC0_CH2_PORT  GPIOA
#define G3507_ADC0_CH2_PIN   DL_GPIO_PIN_25
#define G3507_ADC0_CH2_IOMUX IOMUX_PINCM55

#define G3507_ADC1_CH5_PORT  GPIOB
#define G3507_ADC1_CH5_PIN   DL_GPIO_PIN_18
#define G3507_ADC1_CH5_IOMUX IOMUX_PINCM44

#define HW_ADC_MAP(X) \
    X(API_ADC1, API_ADC_CH2, G3507_ADC0_CH2_PORT, G3507_ADC0_CH2_PIN) \
    X(API_ADC2, API_ADC_CH5, G3507_ADC1_CH5_PORT, G3507_ADC1_CH5_PIN)

/* 软件 I2C1： GPIOB PB2(SCL)/PB3(SDA) */
#define HW_I2C1_SCL_PORT GPIOB
#define HW_I2C1_SCL_PIN  DL_GPIO_PIN_2
#define HW_I2C1_SCL_IOMUX IOMUX_PINCM15 /* PB2 */
#define HW_I2C1_SDA_PORT GPIOB
#define HW_I2C1_SDA_PIN  DL_GPIO_PIN_3
#define HW_I2C1_SDA_IOMUX IOMUX_PINCM16 /* PB3 */

/* 软件 I2C2：GPIOA PA1(SCL)/PA0(SDA) */
#define HW_I2C2_SCL_PORT GPIOA
#define HW_I2C2_SCL_PIN  DL_GPIO_PIN_1
#define HW_I2C2_SCL_IOMUX IOMUX_PINCM2  /* PA1 */
#define HW_I2C2_SDA_PORT GPIOA
#define HW_I2C2_SDA_PIN  DL_GPIO_PIN_0
#define HW_I2C2_SDA_IOMUX IOMUX_PINCM1  /* PA0 */

/* I2C 板级映射：注册 2 路软件 I2C。 */
#define HW_I2C_MAP(X) \
    X(API_I2C1, HW_I2C1_SCL_PORT, HW_I2C1_SCL_PIN, HW_I2C1_SDA_PORT, HW_I2C1_SDA_PIN, HW_I2C1_SCL_IOMUX, HW_I2C1_SDA_IOMUX) \
    X(API_I2C2, HW_I2C2_SCL_PORT, HW_I2C2_SCL_PIN, HW_I2C2_SDA_PORT, HW_I2C2_SDA_PIN, HW_I2C2_SCL_IOMUX, HW_I2C2_SDA_IOMUX)

/* 软件 SPI1：SCK=PB9，MOSI=PB8，MISO=PB7，CS=PB14 */
#define HW_SPI1_SCK_PORT  GPIOB
#define HW_SPI1_SCK_PIN   DL_GPIO_PIN_9
#define HW_SPI1_SCK_IOMUX IOMUX_PINCM26

#define HW_SPI1_MOSI_PORT GPIOB
#define HW_SPI1_MOSI_PIN  DL_GPIO_PIN_8
#define HW_SPI1_MOSI_IOMUX IOMUX_PINCM25

#define HW_SPI1_MISO_PORT GPIOB
#define HW_SPI1_MISO_PIN  DL_GPIO_PIN_6
#define HW_SPI1_MISO_IOMUX IOMUX_PINCM23

#define HW_SPI1_CS_PORT   GPIOA
#define HW_SPI1_CS_PIN    DL_GPIO_PIN_13
#define HW_SPI1_CS_IOMUX  IOMUX_PINCM35

/* SPI 板级映射：注册 1 路软件 SPI。 */
#define HW_SPI_MAP(X) \
        X(API_SPI1, HW_SPI1_CS_PORT, HW_SPI1_CS_PIN, \
            HW_SPI1_SCK_PORT, HW_SPI1_SCK_PIN, \
            HW_SPI1_MOSI_PORT, HW_SPI1_MOSI_PIN, \
            HW_SPI1_MISO_PORT, HW_SPI1_MISO_PIN, HW_SPI1_CS_IOMUX, HW_SPI1_SCK_IOMUX, HW_SPI1_MOSI_IOMUX, HW_SPI1_MISO_IOMUX)

/* OLED SPI 控制引脚定义：DC=PB11，RES=PB10 */
#define HW_OLED_DC_PORT  GPIOB
#define HW_OLED_DC_PIN   DL_GPIO_PIN_11
#define HW_OLED_DC_IOMUX IOMUX_PINCM28

#define HW_OLED_RES_PORT  GPIOB
#define HW_OLED_RES_PIN   DL_GPIO_PIN_10
#define HW_OLED_RES_IOMUX IOMUX_PINCM27

/* OLED SPI 控制引脚映射：注册 1 组 DC/RES。 */
#define HW_OLED_SPI_CTRL_MAP(X) \
	X(HW_OLED_DC_PORT, HW_OLED_DC_PIN, HW_OLED_RES_PORT, HW_OLED_RES_PIN)

/* MPU6050 INT 板级映射：PB4，对应 IOMUX_PINCM17。 */
#define HW_MPU6050_INT_PORT  GPIOB
#define HW_MPU6050_INT_PIN   DL_GPIO_PIN_25
#define HW_MPU6050_INT_IOMUX IOMUX_PINCM56

/* TB6612 板级映射：PWMA=PA16(TIMA1 CCP1), PWMB=PA17(TIMA1 CCP0), AIN1=PA14, AIN2=PA15, BIN1=PA12, BIN2=PA13。 */
#define HW_TB6612_AIN1_PORT   GPIOA
#define HW_TB6612_AIN1_PIN    DL_GPIO_PIN_18
#define HW_TB6612_AIN2_PORT   GPIOA
#define HW_TB6612_AIN2_PIN    DL_GPIO_PIN_15
#define HW_TB6612_BIN1_PORT   GPIOA
#define HW_TB6612_BIN1_PIN    DL_GPIO_PIN_22
#define HW_TB6612_BIN2_PORT   GPIOB
#define HW_TB6612_BIN2_PIN    DL_GPIO_PIN_22

#define HW_TB6612_MAP(X) \
    X(HW_TB6612_AIN1_PORT, HW_TB6612_AIN1_PIN, \
      HW_TB6612_AIN2_PORT, HW_TB6612_AIN2_PIN, \
      HW_TB6612_BIN1_PORT, HW_TB6612_BIN1_PIN, \
      HW_TB6612_BIN2_PORT, HW_TB6612_BIN2_PIN)

/* 编码器 1 */
#define HW_ENCODER1_A_PORT GPIOA
#define HW_ENCODER1_A_PIN  DL_GPIO_PIN_24
#define HW_ENCODER1_B_PORT GPIOA
#define HW_ENCODER1_B_PIN  DL_GPIO_PIN_25

/* 编码器 2 */
#define HW_ENCODER2_A_PORT GPIOB
#define HW_ENCODER2_A_PIN  DL_GPIO_PIN_26
#define HW_ENCODER2_B_PORT GPIOB
#define HW_ENCODER2_B_PIN  DL_GPIO_PIN_27

#define HW_ENCODER_MAP(X) \
    X(API_ENCODER_1, API_ENCODER_CORE_ENC0, \
      0U, HW_ENCODER1_A_PORT, HW_ENCODER1_A_PIN, \
      0U, HW_ENCODER1_B_PORT, HW_ENCODER1_B_PIN) \
    X(API_ENCODER_2, API_ENCODER_CORE_ENC1, \
      0U, HW_ENCODER2_A_PORT, HW_ENCODER2_A_PIN, \
      0U, HW_ENCODER2_B_PORT, HW_ENCODER2_B_PIN)

/* 当前板子上注册了 4 个LED */
#define HW_LED_COUNT    4U
/* 当前板子上注册了 4 个按键 */
#define HW_KEY_COUNT    4U
/* 当前板子上注册了 3 路 USART */
#define HW_USART_COUNT  3U
/* 当前板子上注册了 1 路 PWM（2 个输出通道） */
#define HW_PWM_COUNT    2U
/* 当前板子上注册了 3 路 TIM */
#define HW_TIM_COUNT    3U
/* 当前板子上注册了 1 路 ADC */
#define HW_ADC_COUNT  2U
/* 当前板子上注册了 2 路软件 I2C */
#define HW_I2C_COUNT  2U
/* 当前板子上注册了 1 路软件 SPI */
#define HW_SPI_COUNT  1U
/* 当前板子上注册了 1 组 OLED SPI 控制引脚 */
#define HW_OLED_SPI_CTRL_COUNT  1U
/* 当前板子上注册了 1 路 MPU6050 INT 引脚 */
#define HW_MPU6050_COUNT 1U
/* 当前板子上注册了 1 路 TB6612 电机驱动 */
#define HW_TB6612_COUNT 1U
/* 当前板子上注册了 2 个编码器 */
#define HW_ENCODER_COUNT  2U

#endif /* __G3507_HW_CONFIG_H */
